### ISSUE TITLE
 Create a cron job to call the v2 endpoint to retrieve the approved list and send the v2 list via email to EGA

### ISSUE THREAD

**Issue by akachru-github** [icgc-argo/dac-roadmap#1]
- The v1 list that is sent today will not be touched. 
- This is a new job that will send the v2 list. 

Build TSV file -> encrypt it -> send email

- Requires encryption key? Let's discuss
- Might need work to extend request sender to get client creds token from Ego. Needs to be confirmed. 
  - Integrate with vault, get client secret

**Comment by akachru-github** [comment]
@blabadi  and @anncatton  to discuss further on encryption needs.

**Comment by anncatton** [comment]
Node uses openssl 1.1.1, so the encrypted output from the dac-api email will need to be decrypted with the same version. (I tried a working command with a different version, LibreSSL 2.8.3 and got `bad decrypt` errors). We need to verify what version of openssl ega is using.
References:
https://nodejs.org/ru/blog/vulnerability/april-2020-openssl-updates/
https://nodejs.org/en/blog/release/v16.14.2/

**Comment by blabadi** [comment]
I think we also need to verify that it will work on our daco2ego vm as well. I'll share the version info on slack

**Comment by blabadi** [comment]
deployed and tested in prod
